### PR TITLE
Work on #295

### PR DESCRIPTION
**Pull request by cont1nuity**
- [x] Adding timer description text and related options
- [x] Adding additional options for timer
- [x] Adding options for anchor/positioning

This satisfies part of the open topics from #295

### CODE REVIEW

**Comment by cont1nuity** [comment]
I want to split the anchor and growth direction option. After that, this should be ready for review.

**Comment by cont1nuity** [comment]
Options added:
image

**Comment by cont1nuity** [comment]
Options for enable/disable text and timer are still missing.

**Comment by cont1nuity** [comment]
@MysticalOS: this is ready for review now.

**Review by QartemisT — APPROVED** [review]

**Pull request merged**
