### PR TITLE
Core: fix wrong math on enrage timer prototype

### PR DESCRIPTION
**Pull request by Zidras**
If timer was negative, for example :Start(-delay), minus with minus was plus

### CODE REVIEW

**Comment by MysticalOS** [comment]
what exactly are you trying to fix. the -delay part is subtracking combat delay (if mod was started by something other than ENCOUNTER_START)
usually it's 0 though. but even if delay was up to 3 seconds. what enrage timer is less than 3 seconds? none in entirey of wow. no boss is gonna have a 3 second boss enrage so there will never ever be a negative engage timer

**Comment by Zidras** [comment]
The problem is not the negative enrage timer, but the intention of subtracting :Start(-delay), which is a negative number (example: -0,5 from PRD) to the timer in the prototype, which is coded as `- timer` so in reality the math is doing the opposite `- (- timer) `, which turns into an addition `+ timer`. 
To fix the math, all I did was make the delay factor absolute, so it is always a valid subtraction of a positive value. 

Is this now more clear?

**Comment by MysticalOS** [comment]
I still don't see what logic you're trying to fix. the way lua works, the only thing the timer object sees is the modified number
it's not like :start is being called with number - number. it's just being called with number cause the arithmetic was already done

so the object will only ever see a whole positive number.

**Comment by Mitalie** [comment]
A negative timer parameter is passed as `enrageTimer:Start(-delay)` in many mods' `function mod:OnCombatStart(delay)` where a nonzero (positive) delay indicates that the fight had already started before the mod activated. If the mod activates e.g. 3 seconds into a fight with 600 seconds berserk timer, then the berserk timer should have 597 seconds remaining, right? But `self.timer - timer` = `600 - -3` = `603`.

Compare with `timerPrototype:Start()` where `600 + -3` = `597` at https://github.com/DeadlyBossMods/DBM-Unified/blob/ade284adb4f5191cb4840778c1432810df313e15/DBM-Core/DBM-Core.lua#L10050

It looks like this adjustment in `enragePrototype:Start` has been backwards since it was added in Nov 2008: https://github.com/DeadlyBossMods/DBM-Retail/commit/2be9c23fa92eb4505922ee11fdd5347558806927. I can imagine it going unnoticed because seeing the enrage happen is not that common, many enrages aren't instant wipes so the exact moment isn't that noticeable especially when focusing on mechanics and/or the boss's HP, and in modern world with ENCOUNTER_START (and IEEU before that) the delay is typically zero anyway.

**Comment by Zidras** [comment]
> A negative timer parameter is passed as `enrageTimer:Start(-delay)` in many mods' `function mod:OnCombatStart(delay)` where a nonzero (positive) delay indicates that the fight had already started before the mod activated. If the mod activates e.g. 3 seconds into a fight with 600 seconds berserk timer, then the berserk timer should have 597 seconds remaining, right? But `self.timer - timer` = `600 - -3` = `603`.
> 
> Compare with `timerPrototype:Start()` where `600 + -3` = `597` at
> 
> https://github.com/DeadlyBossMods/DBM-Unified/blob/ade284adb4f5191cb4840778c1432810df313e15/DBM-Core/DBM-Core.lua#L10050
> 
> It looks like this adjustment in `enragePrototype:Start` has been backwards since it was added in Nov 2008: [DeadlyBossMods/DBM-Retail@2be9c23](https://github.com/DeadlyBossMods/DBM-Retail/commit/2be9c23fa92eb4505922ee11fdd5347558806927). I can imagine it going unnoticed because seeing the enrage happen is not that common, many enrages aren't instant wipes so the exact moment isn't that noticeable especially when focusing on mechanics and/or the boss's HP, and in modern world with ENCOUNTER_START (and IEEU before that) the delay is typically zero anyway.
> 
> I'd just swap the minus for a plus instead of bringing `math.abs` into play, though.

Exactly, thank you @Mitalie for explaining it.
And just to voice my opinion, a + also works, but I ultimately decided to write abs for readability, since later down the line someone could probably find strange to find an addition there, because we want to subtract a value to self.timer

**Pull request merged**
