### PR TITLE
Update localization.ru.lua

### PR DESCRIPTION
**Pull request by Hollicsh**
A few amendments.

### CODE REVIEW

**Comment by Molkree** [comment]
I think tabs are preferred to whitespaces in Lua 🤔

**Comment by Hollicsh** [comment]
> I think tabs are preferred to whitespaces in Lua 🤔

Что ты имеешь ввиду ? )

**Comment by MysticalOS** [comment]
Some of the tabs were changed to spaces in edit. I'm surprised it actually passed lua check, but i guess it only runs basic on pull requests. what are you using to edit the files?

**Comment by Hollicsh** [comment]
> Some of the tabs were changed to spaces in edit. I'm surprised it actually passed lua check, but i guess it only runs basic on pull requests. what are you using to edit the files?

I understood what it was about.
Actually, I didn't touch it. I just changed a couple of phrases and added one more and that's it.
I don't know how it happened =\
I use simple Notepad++ for editing.

**Comment by MysticalOS** [comment]
It's likely a setting in your editor. try to find setting for spaces versus tabs. what will happen is any line you edit, your editor will change spacing based on it's config.

**Review by MysticalOS — APPROVED** [review]

**Comment by Hollicsh** [comment]
> It's likely a setting in your editor. try to find setting for spaces versus tabs. what will happen is any line you edit, your editor will change spacing based on it's config.

Okay sorry.
I'll look in Notepad++ settings.

**Pull request merged**
