### PR TITLE
Send fake BigWigs messages to WeakAuras BW triggers

### PR DESCRIPTION
**Pull request by Mitalie**
Creating a draft PR for preliminary review. Still needs:
* Not injecting fake API at all if BW is loaded, as it'd prevent WA from receiving actual BW messages.
* Creating and checking a toggle, in case user doesn't need it and it causes unwanted side effects in e.g. auras that support both BW and DBM
* Defaulting to disabled if BW installed, enabled if not installed.
* Inserting compatibility config in mods
* Testing

All compatibility data is looked up from `mod.bwCompat` table.
```lua
local mod = DBM:NewMod(...)
local timerSomething = mod:NewCDTimer(15, 401234, ...)
local warnSomething = mod:NewSpecialWarningYou(401234, ...)
mod.bwCompat = {
  useStageTotality = true, -- send vb.stageTotality instead of vb.phase (default)
  stageMap = { -- if a more complicated translation is needed, keyed by either vb.phase or vb.stageTotality based on useStageTotality
    [2.5] = 3
    [3] = 4
  },
  keys = {
    [401234] = 401235, -- translate all announces/SWs/timers with 401234 to 4012345
    [warnSomething] = 401236, -- translate just this warning to 401236 instead, if DBM happened to use same ID on two objects but BW didn't
  },
}
```

### CODE REVIEW

**Comment by MysticalOS** [comment]
Why was this added to bar update call?
`removeEntry(self.startedTimers, id)`
this will brick being able to stop or update bar again afterwards since it'll no longer have an internal reference in core

**Comment by MysticalOS** [comment]
Oh nice, we were only doing this because of time tabel given beeing 11.0

**Comment by Stanzilla** [comment]
> Oh nice, we were only doing this because of time tabel given beeing 11.0

who gave you which time table?

**Comment by Mitalie** [comment]
If the unified trigger lands soon enough, we'll scrap the BW event emulation (and plan to scrap it after Dragonflight anyway), but `DBM:GetBWKey()` and the mapping table it uses may be useful in making the unified trigger work in Vault and Aberrus as the current IDs can't be changed without breaking working auras and resetting user settings for those abilities.

**Review by MysticalOS — APPROVED** [review]

**Pull request merged**
